#! /usr/bin/env bash
hidecursor() { printf "\x1b[?25l"; }
showcursor() { printf "\x1b[?25h"; }
locate() { printf "\x1b[%i;%iH" "$1" "$2"; }

hidecursor
stty -echo
clear

trap 'showcursor; stty echo; echo -e "\rdone."; exit' INT

while :; do
  locate 0 0
  netspeed
  sleep 1
done
